ftype code="C:\Users\aslater\vimfiles\gvim_remote.bat" "%%1"
ftype txtfile="C:\Users\aslater\vimfiles\gvim_remote.bat" "%%1"
REM ftype code=gvim --remote-tab-silent "%%1"
REM ftype txtfile=gvim --remote-tab-silent "%%1"
assoc .c=code
assoc .C=code
assoc .cpp=code
assoc .c++=code
assoc .h=code
assoc .H=code
assoc .hpp=code
assoc .vimrc=code
assoc .gvimrc=code
assoc .mk=code
assoc .mak=code
assoc .cmake=code
assoc .py=code
assoc .pl=code
assoc .xml=code
assoc .java=code
assoc .vimrc=code
assoc .gvimrc=code
assoc .sh=code
assoc .bkl=code
assoc .cfg=code
